"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 4

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5C2E7"
lavender = "#B4BEFE"
blue = "#89B4FA"
go_blue = "#89DCEB"
py_yellow = "#F9E2AF"

[[blocks]]
alignment = "left"
type = "prompt"
  [[blocks.segments]]
    foreground = "p:blue"
    style = "plain"
    template = "{{ .UserName }}:{{ .HostName }} "
    type = "session"
  [[blocks.segments]]
    foreground = "p:pink"
    style = "plain"
    template = "{{ .Path }} "
    type = "path"
    [blocks.segments.options]
    style = "full"
  [[blocks.segments]]
    foreground = "p:lavender"
    template = "{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} {{ .Working.String }}{{ if and (.Working.Changed) (.Staging.Changed) }}|{{ end }}{{ .Staging.String }}{{ end }} "
    style = "plain"
    type = "git"
  [blocks.segments.properties]
    branch_icon = " "
    cherry_pick_icon = " "
    commit_icon = " "
    fetch_status = true
    fetch_upstream_icon = true
    merge_icon = " "
    no_commits_icon = " "
    rebase_icon = " "
    revert_icon = " "
    tag_icon = " "

[[blocks]]
alignment = "right"
type = "prompt"
  [[blocks.segments]]
      type = "go"
      style = "plain"
      foreground = "p:go_blue"  # 使用新定義的 Go 藍
      template = " {{ .Full }} "
      [blocks.segments.properties]
        display_mode = "files"

    [[blocks.segments]]
      type = "python"
      style = "plain"
      foreground = "p:py_yellow" # 使用新定義的 Python 黃
      template = " {{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }} "
      [blocks.segments.properties]
        display_mode = "context"
        fetch_virtual_env = true

[[blocks]]
alignment = "left"
type = "prompt"
newline = true # 這行是關鍵，強制換行
  [[blocks.segments]]
    foreground = "p:closer"
    style = "plain"
    template = ""
    type = "text"

[maps.user_name]
szelam = "󰊠"
root = ""

[maps.host_name]
szelamMacBookPro = ""
