#!/usr/bin/env sh
# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config debug_output off
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_animation_duration 0.1
yabai -m config window_animation_frame_rate 60
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config top_padding 06
yabai -m config bottom_padding 06
yabai -m config left_padding 06
yabai -m config right_padding 06
yabai -m config window_gap 06
yabai -m config layout bsp
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config external_bar all:38:0

# custom rule
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Cursor Pro$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^zoom.us$" mouse_follows_focus=on
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off layer=below
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

"yabai configuration loaded.."
