return {
  { "dashboard-nvim", enabled = false },
  { "mini.ai", enabled = false },
  { "mini.comment", enabled = false },
  { "mini.indentscope", enabled = false },
  { "mini.pairs", enabled = false },
  { "neo-tree.nvim", enabled = false },
  { "neoconf.nvim", enabled = false },
  { "nvim-notify", enabled = false },
  { "persistence.nvim", enabled = false },
  { "vim-illuminate", enabled = false },
  { "trouble.nvim", enabled = false },
  { "nvim-treesitter-context", enabled = false },
  { "nvim-spectre", enabled = false },
  { "mini.surround", enabled = false },
}
